### ISSUE TITLE
Can we decouple express from this repo?

### ISSUE THREAD

**Issue by subhendukundu** [gigantz/reactend-express#17]
I was spending the day trying to decouple the express from the app (I failed 😔 ).
If we can do that, it will support quite a few cases where express is not supported.
For example, Cloudflare workers.

**Comment by gigantz** [comment]
what did you plan to connect with?
any framework?

**Comment by subhendukundu** [comment]
https://developers.cloudflare.com/workers/
This one. I can contribute too. But need help to get started.

**Comment by gigantz** [comment]
Sure, go ahead, create PR for that.
Just let me know which problem you faced

**Comment by subhendukundu** [comment]
Awesome! One thing I need help, if you can decouple the express. Is that something possible?
Then I can try on the same with Cloudflare worker, or Koa etc

**Comment by devhammed** [comment]
> Awesome! One thing I need help, if you can decouple the express. Is that something possible?
> Then I can try on the same with Cloudflare worker, or Koa etc

This should be possible, you just need an entry point.
