### ISSUE TITLE
How to use without template

### ISSUE THREAD

**Issue by 1nfinity-5starZ** [gigantz/reactend-express#18]
I'm trying to implement it alongside my existing project, I don't want to start from scratch with the template.

However I'm getting an error, could you please provide information on how to use it ?

![image](https://user-images.githubusercontent.com/19469895/109428442-7282f480-79f7-11eb-8335-c85b1213caa3.png)

**Comment by gigantz** [comment]
Can you provide a part of the code where you're implement it?

Check these in the repo https://github.com/reactend/reactend-template:
- There's a `/index.js` with `babel-register` as @reactend/express uses jsx
- package.json for dependencies you'll have to install
- `/src/app.js` is an example of how it should look like

**Comment by 1nfinity-5starZ** [comment]
Thanks for the response.

I tried to implement it alongside my React SPA, created using create-react-app.

I checked the reactend-template repo, made sure to install all the dependencies.

I copied the code in '/index.js' with babe-register to my root React root file '/index.jsx'.

 The '/src/app.js' was copied to a different file, but I made sure to point to it in my 'index.jsx' 

Does that make sense ?

I'll revert the changes and try to post the actual code here.

**Comment by gigantz** [comment]
It makes perfect sense, it should work.
But unfortunately, your SPA will not work as it works in next.js for example.
Sure you can add your app created with `create-react-app` in route, adding bundle script and etc.

This feature is on the way, but it's not that easy, cause this is mostly http-server

**Comment by 1nfinity-5starZ** [comment]
Thanks for the info, I'll close the issue
