### ISSUE TITLE
Polka / tinyhttp integration

### ISSUE THREAD

**Issue by v1rtl** [gigantz/reactend-express#5]
Would be cool to be able to have examples of using react-xpress with other Express like frameworks (if it's possible)

also it'd be better if express would be a peer dep so it's easier to alias modules (like when you replace React with Preact in a Next.js app)

**Comment by gigantz** [comment]
Yeah, I'll do some change to use it in a better way (peer deps and etc.) and it needs to be npm package
It's a good idea about integrate express-like frameworks, I have an experience with koa and nestjs. So, I'll need to read polka/tinyhttp docs :)

**Comment by v1rtl** [comment]
@gigantz Polka is basically Express without req / res extensions, tinyhttp is Express remake w/ different app settings but with all extensions

so should be easy to integrate them (theoretically)

**Comment by v1rtl** [comment]
why has this been closed?
