### ISSUE TITLE
How to test locally?

### ISSUE THREAD

**Issue by Myzel394** [gigantz/reactend-express#8]
Hi,

so I'm trying to test this project locally but can't seem to get React working. When I use JSX, there's an SyntaxError, when I rename the file to .jsx, there's an TypeError:

```
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".jsx" for /path/to/the/file.jsx
```

maybe you could add a little tutorial on how to setup everything locally? This way, everyone could contribute to this project :)

**Comment by gigantz** [comment]
Hi,
jsx extension not supported yet, please use js
I’ll create a quick tutorial soon.

**Comment by Myzel394** [comment]
```
npx create-reactend my-app
```

raises this error:

```
npx: installed 9 in 2.389s
Cannot find module 'execa'
Require stack:
- /path/to/node_modules/create-reactend/create-reactend.js
```

**Comment by gigantz** [comment]
Please try to clone this https://github.com/gigantz/reactend-template
I'll fix this `create-reactend` error

**Comment by Myzel394** [comment]
Thank you, I already cloned it but I want to contribute to reactend-express ;D

**Comment by gigantz** [comment]
Sure, feel free to create PRs with ideas/updates/fixes!
btw. I fixed `npx create-reactend my-app`. Please check it also
